"""initial schema: shows, seasons, episodes, artwork, publish runs, users

Autogenerated then hand-checked. Two edits were needed and matter:

* The enum types are created **once**, up front, instead of inline in each
  ``create_table`` — ``publication_status`` is used by both ``shows`` and
  ``episodes``, and the generated version tried to create it twice.
* All timestamps are ``timestamptz``. Publish-run history is compared across
  environments; naive local time makes that a guessing game.
* The title indexes are ``pg_trgm`` GIN on the raw column rather than btrees on
  ``lower(title)``: search is substring, a btree is never chosen for
  ``LIKE '%kite%'``, and indexing the raw column serves ``ILIKE`` too.

``pg_trgm`` is a contrib extension. It ships with Postgres and with the official
image, but on a managed instance the app role may not be allowed to
``CREATE EXTENSION`` — have a DBA enable it once before running this migration.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-20
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

publication_status = postgresql.ENUM(
    "draft", "published", name="publication_status", create_type=False
)
artwork_kind = postgresql.ENUM(
    "poster", "banner", "thumbnail", name="artwork_kind", create_type=False
)
publish_run_status = postgresql.ENUM(
    "running", "succeeded", "failed", name="publish_run_status", create_type=False
)
user_role = postgresql.ENUM("editor", "admin", name="user_role", create_type=False)

_ENUMS = (publication_status, artwork_kind, publish_run_status, user_role)


def upgrade() -> None:
    bind = op.get_bind()
    # Substring search over titles needs trigram indexes; pg_trgm ships with Postgres.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for enum in _ENUMS:
        enum.create(bind, checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", user_role, nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_users_token_hash")),
    )

    op.create_table(
        "shows",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("synopsis", sa.Text(), server_default="", nullable=False),
        sa.Column("section", sa.String(length=40), nullable=True),
        sa.Column(
            "categories",
            postgresql.ARRAY(sa.String(length=40)),
            server_default=sa.text("'{}'::varchar[]"),
            nullable=False,
        ),
        sa.Column("status", publication_status, server_default="draft", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shows")),
        sa.UniqueConstraint("slug", name=op.f("uq_shows_slug")),
    )
    # The CMS list filters published shows by section; drafts are the majority of rows in
    # a working CMS, so the index only covers the rows those queries can return.
    op.create_index(
        "ix_shows_section_published",
        "shows",
        ["section"],
        unique=False,
        postgresql_where=sa.text("status = 'published'"),
    )
    # Search is case-insensitive substring matching. A btree on lower(title) is never
    # chosen by the planner; a trigram GIN on the raw column serves ILIKE and LIKE both.
    op.create_index(
        "ix_shows_title_trgm",
        "shows",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # The CMS list searches title OR slug; an index on only one of them is an index on
    # neither, because the OR forces a scan.
    op.create_index(
        "ix_shows_slug_trgm",
        "shows",
        ["slug"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"slug": "gin_trgm_ops"},
    )

    op.create_table(
        "seasons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("show_id", sa.UUID(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "season_number >= 0", name=op.f("ck_seasons_season_number_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_seasons_show_id_shows"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("show_id", "season_number", name="uq_seasons_show_id_season_number"),
    )

    op.create_table(
        "episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("content_group", sa.String(length=160), nullable=False),
        sa.Column("status", publication_status, server_default="draft", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds > 0",
            name=op.f("ck_episodes_duration_seconds_positive"),
        ),
        sa.CheckConstraint(
            "episode_number >= 0", name=op.f("ck_episodes_episode_number_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_episodes_season_id_seasons"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episodes")),
        # The brief's rule, enforced where concurrent editors cannot dodge it.
        sa.UniqueConstraint("content_group", "language", name="uq_episodes_content_group_language"),
        # Language variants share (season, number) by design; two English S1E4s do not.
        sa.UniqueConstraint(
            "season_id",
            "episode_number",
            "language",
            name="uq_episodes_season_id_episode_number_language",
        ),
        sa.UniqueConstraint("external_id", name=op.f("uq_episodes_external_id")),
    )
    op.create_index(
        "ix_episodes_season_id_episode_number", "episodes", ["season_id", "episode_number"]
    )
    # Publish collapses variants by content_group, but that needs no index of its own:
    # uq_episodes_content_group_language is a btree led by content_group and serves it.
    op.create_index(
        "ix_episodes_title_trgm",
        "episodes",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )

    op.create_table(
        "artwork",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", artwork_kind, nullable=False),
        sa.Column("show_id", sa.UUID(), nullable=True),
        sa.Column("episode_id", sa.UUID(), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(show_id IS NULL) <> (episode_id IS NULL)",
            name=op.f("ck_artwork_artwork_has_exactly_one_owner"),
        ),
        # Posters and banners describe a show; thumbnails describe an episode.
        sa.CheckConstraint(
            "(show_id IS NOT NULL AND kind IN ('poster', 'banner')) "
            "OR (episode_id IS NOT NULL AND kind = 'thumbnail')",
            name=op.f("ck_artwork_artwork_kind_matches_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
            name=op.f("fk_artwork_episode_id_episodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["show_id"], ["shows.id"], name=op.f("fk_artwork_show_id_shows"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artwork")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_artwork_storage_key")),
    )
    # One poster per show, one thumbnail per episode — partial because the other
    # owner column is NULL and NULLs would otherwise not collide.
    op.create_index(
        "uq_artwork_show_id_kind",
        "artwork",
        ["show_id", "kind"],
        unique=True,
        postgresql_where=sa.text("show_id IS NOT NULL"),
    )
    op.create_index(
        "uq_artwork_episode_id_kind",
        "artwork",
        ["episode_id", "kind"],
        unique=True,
        postgresql_where=sa.text("episode_id IS NOT NULL"),
    )

    op.create_table(
        "publish_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("status", publish_run_status, server_default="running", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_by_email", sa.String(length=320), nullable=False),
        sa.Column("catalog_key", sa.String(length=512), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "counts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("blocker_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        # A reuse and a rollback both produce a "succeeded" run that did not build
        # anything new; the CMS has to tell those apart in the history.
        sa.Column("reused_previous_key", sa.String(length=512), nullable=True),
        sa.Column("rolled_back_to_run_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_publish_runs_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["rolled_back_to_run_id"],
            ["publish_runs.id"],
            name=op.f("fk_publish_runs_rolled_back_to_run_id_publish_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publish_runs")),
    )
    # Run history is always "newest first"; a plain btree scans backwards for that.
    op.create_index("ix_publish_runs_started_at", "publish_runs", ["started_at"])
    # At most one publish in flight, enforced by Postgres rather than by hoping.
    op.create_index(
        "uq_publish_runs_one_running",
        "publish_runs",
        ["status"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )


def downgrade() -> None:
    op.drop_index(
        "uq_publish_runs_one_running",
        table_name="publish_runs",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index("ix_publish_runs_started_at", table_name="publish_runs")
    op.drop_table("publish_runs")
    op.drop_index(
        "uq_artwork_episode_id_kind",
        table_name="artwork",
        postgresql_where=sa.text("episode_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_artwork_show_id_kind",
        table_name="artwork",
        postgresql_where=sa.text("show_id IS NOT NULL"),
    )
    op.drop_table("artwork")
    op.drop_index("ix_episodes_title_trgm", table_name="episodes", postgresql_using="gin")
    op.drop_index("ix_episodes_season_id_episode_number", table_name="episodes")
    op.drop_table("episodes")
    op.drop_table("seasons")
    op.drop_index("ix_shows_slug_trgm", table_name="shows", postgresql_using="gin")
    op.drop_index("ix_shows_title_trgm", table_name="shows", postgresql_using="gin")
    op.drop_index(
        "ix_shows_section_published",
        table_name="shows",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_table("shows")
    op.drop_table("users")

    bind = op.get_bind()
    for enum in _ENUMS:
        enum.drop(bind, checkfirst=True)
